env:
  JULIA_NUM_THREADS: auto

secrets:
  - CODECOV_TOKEN

steps:
  - label: General tests
    plugins:
      - QuantumSavory/julia#v1:
          version: "1.12"
      - JuliaCI/julia-test#v1:
          test_args: "general"
      - JuliaCI/julia-coverage#v1: ~

  - label: JET tests
    plugins:
      - QuantumSavory/julia#v1:
          version: "1.12"
      - JuliaCI/julia-test#v1:
          test_args: "jet"
      - JuliaCI/julia-coverage#v1: ~

  - label: Tyler tests
    plugins:
      - QuantumSavory/julia#v1:
          version: "1.12"
      - JuliaCI/julia-test#v1:
          test_args: "tyler"
      - JuliaCI/julia-coverage#v1: ~
    secrets:
      - TILE_CI_KEY

  - label: Docs
    branches: "!dependabot/*"
    plugins:
      - QuantumSavory/julia#v1:
          version: "1.12"
    secrets:
      DOCUMENTER_KEY: DOCUMENTER_KEY_CommunicationNetworkDatasets
      TILE_CI_KEY: TILE_CI_KEY
    command: |
      julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      julia -tauto --project=docs docs/make.jl
